Add carbon components
ibm-frontend/gatsby-starter-carbon pull request #20
Opened 2017-12-19 19:56 UTC by tworkman512

**What kind of change does this PR introduce?**

- Added `carbon-components-react`, `carbon-components`, and `carbon-icons` as dependencies. 
- Added basic `tile` Carbon react component in the About page. 
- Added `carbon-component` global styles.

**Did you write unit test?**

No, I'm not sure how to do that and could use some help if that's necessary here.

**Summary**

Carbon React components and styles must be imported to be used in creating a Gatsby site. See issue here for more context: https://github.com/ibm-frontend/gatsby-starter-carbon/issues/6

**Other information**

Please note, that I chose to import the `tile` Carbon styling directly here temporarily until we add the global styling for Carbon. 

Also, I'm not 100% certain that I added the Carbon global styles correctly and would appreciate someone checking that and offering any guidance if needed. I didn't remove the Material Design styling yet, as that would break pretty much every style in the UI at this point.

2018-01-31 03:12 UTC, diego-codes submitted a review, later dismissed

2018-01-31 03:39 UTC, diego-codes requested changes
@tworkman512 sorry it took so long to review this! It's looking good 👍 . Just some minor changes to make. Let me know if you have time to address these or have any questions.

2018-01-31 03:39 UTC, diego-codes commented on src/components/About/About.jsx
> +import { Tile } from "carbon-components-react/lib/components/Tile";
- [ ] The `Tile` component can be imported more easily by importing from `"carbon-components-react"`, the package already knows how to find the right component file.

2018-01-31 03:39 UTC, diego-codes commented on src/components/About/About.jsx
> +				<Tile>
- [ ] Can you reformat the indentation in the `Tile` code to be 2 spaces instead of tabs please?

2018-01-31 03:39 UTC, diego-codes commented on src/layouts/index.scss
> +@import '~carbon-components/scss/globals/grid/_grid.scss';
- [ ] It took some digging around, but it looks like there is a way to import all of the styles:
```scss
@import '~carbon-components/scss/globals/scss/styles';
```

2018-01-31 03:45 UTC, diego-codes commented
Sorry one last comment, can you delete the `package-lock.json` file and create a `yarn.lock` file instead? We're going to be using `yarn` for this project.

2018-02-02 16:28 UTC, tworkman512 commented
@diego-codes made the requested changes and ready for review.

2018-02-04 03:30 UTC, diego-codes approved these changes
Looks good after the minor change requested is addressed.

2018-02-04 03:30 UTC, diego-codes commented on src/layouts/index.scss
> +@import '~carbon-components/scss/globals/grid/_grid.scss';
- [ ] Sorry, I meant to say that you can remove all of the `@import`s of Carbon Components and replace them all with the single `@import`:
```scss
@import '~carbon-components/scss/globals/scss/styles';
```

2018-02-05 22:11 UTC, merged