Refactor/footer
ibm-frontend/gatsby-starter-carbon pull request #39
Opened 2018-02-12 17:53 UTC by diego-codes

**What kind of change does this PR introduce?**

* Refactor Footer component to adhere to Carbon Design System's look and feel.
* Optimize Footer component code to remove unused features and adhere to BEM class naming conventions.

2018-02-16 18:53 UTC, kellychurchill requested changes
Looks good except that there is a typo in the userLinks data in data/SiteConfig.js https://github.com/https://github.com/ibm-frontend/

2018-02-16 19:40 UTC, kellychurchill commented
Also, I was prompted to install the following - should these get added to the package.json? 
`carbon-components-react`
`react-disqus-comments`

2018-03-01 04:39 UTC, diego-codes commented
@kellychurchill fixed your what you requested, it's ready for your review again.

2018-04-09 21:20 UTC, kellychurchill approved these changes

2018-04-09 21:20 UTC, merged