feat(Navigation): carbon-ify the header and left nav
ibm-frontend/gatsby-starter-carbon pull request #42
Opened 2018-03-21 14:39 UTC by ryanomackey

**What kind of change does this PR introduce?**

Carbonizes the header and left nav:

<img width="536" alt="screen shot 2018-03-21 at 9 29 50 am" src="https://user-images.githubusercontent.com/17710824/37715816-fdcb4a40-2cea-11e8-9272-a5597ea47a13.png">

**Did you write unit test?**

I did not. (Probably deserves a separate PR since we don't have a testing framework set up).

**If relevant, link to documentation update:**

N/A

**Summary**

See #24 

**Other information**

N/A

2018-04-09 21:34 UTC, kellychurchill submitted a review, later dismissed

2018-04-09 21:42 UTC, kellychurchill requested changes

2018-04-09 21:42 UTC, kellychurchill commented on src/components/Navigation/Navigation.jsx
> -import Footer from "../Footer/Footer";
We need to add this back in so the global footer shows up

2018-04-09 21:42 UTC, kellychurchill commented on src/components/Navigation/Navigation.jsx
> -        <Footer userLinks={footerLinks} />
Let's add this back in

2018-05-07 01:07 UTC, ryanomackey commented
@kellychurchill should be all set now 🙂

2018-05-31 19:15 UTC, kellychurchill approved these changes

2018-05-31 19:15 UTC, merged